name: Test Flakiness Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Run test normally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run test
        run: mvn "-Djava.util.secureRandomSeed=true" "-Djdk.map.althashing.threshold=0" edu.illinois:nondex-maven-plugin:2.1.1:nondex "-DnondexRuns=25" "-Dtest=org.json.junit.JSONObjectTest#valueToString" "-DnondexMode=ONE" "-DnondexSeed=0"

  nondex:
    name: Run NonDex across JDK distributions
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: run nondex
        run: mvn "-Djava.util.secureRandomSeed=true" "-Djdk.map.althashing.threshold=0" edu.illinois:nondex-maven-plugin:2.1.1:nondex "-DnondexRuns=25" "-Dtest=org.json.junit.JSONObjectTest#valueToString" "-DnondexMode=FULL"
