name: Test Flakiness Test

on:
  push:
  pull_request:

jobs:
  test:
    name: run test normally
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: run test
        run: mvn "-Djava.util.secureRandomSeed=true" "-Djdk.map.althashing.threshold=0" edu.illinois:nondex-maven-plugin:2.1.1:nondex "-DnondexRuns=25" "-Dtest=org.json.junit.JSONObjectTest#valueToString" "-DnondexMode=ONE" "-DnondexSeed=0"

  nondex:
    name: run nondex tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: run nondex
        run: mvn "-Djava.util.secureRandomSeed=true" "-Djdk.map.althashing.threshold=0" edu.illinois:nondex-maven-plugin:2.1.1:nondex "-DnondexRuns=25" "-Dtest=org.json.junit.JSONObjectTest#valueToString" "-DnondexMode=FULL"
